Changes for run wardend as unprivileged user
warden-protocol/helm-charts pull request #11
Opened 2024-05-29 15:11 UTC by mikolajsobolewski

!!! Changes uncompatible with previous installation. We should do additional testing before deploy it on other networks

2024-05-30 15:34 UTC, mikolajsobolewski commented on charts/wardend/Chart.yaml
> +version: 1.0.0
Changed, but we can use the  latest if we keep changes in container'

2024-05-31 04:21 UTC, jlehtimaki commented on charts/wardend/Chart.yaml
> +version: 1.0.0
We don't have `latest` tags in our containers

2024-05-31 04:31 UTC, jlehtimaki requested changes

2024-05-31 04:31 UTC, jlehtimaki commented on charts/wardend/values.yaml
>    name: node
I'd move this to more logical place.

```suggestion
  enabled: true
  ready: true
  name: node
  home: /data/.warden
```

2024-05-31 07:39 UTC, jlehtimaki approved these changes

2024-05-31 07:47 UTC, merged