Add EIP check
warden-protocol/helm-charts pull request #48
Opened 2024-10-01 14:53 UTC by mikolajsobolewski

2024-10-01 17:46 UTC, jlehtimaki requested changes

2024-10-01 17:46 UTC, jlehtimaki commented on charts/wardend/Chart.yaml
> +version: 2.4.1
```suggestion
version: 2.4.0
```

2024-10-02 07:28 UTC, mikolajsobolewski commented on charts/wardend/values.yaml
> +  retries: 20
I think this might be useful in case of problems with EIP

2024-10-02 09:07 UTC, jlehtimaki commented on charts/wardend/values.yaml
> +  retries: 20
I think it's better that the container does not even start without EIP and like I said, we can use this with the default kubernetes behaviour:
https://kubernetes.io/docs/concepts/workloads/pods/init-containers/#detailed-behavior

2024-10-02 11:33 UTC, mikolajsobolewski commented on charts/wardend/values.yaml
> +  retries: 20
I'd removed retries.

2024-10-02 13:24 UTC, jlehtimaki requested changes

2024-10-02 13:24 UTC, jlehtimaki commented on charts/wardend/scripts/init.sh
> +    if [ -z "$EIP_RETRIES" ]; then
Need to remove the EIP_RETRIES from the script as well

2024-10-02 14:00 UTC, mikolajsobolewski commented on charts/wardend/scripts/init.sh
> +    if [ -z "$EIP_RETRIES" ]; then
Oops, sorry, forgot the duplicate

2024-10-02 15:21 UTC, jlehtimaki approved these changes

2024-10-02 15:26 UTC, merged