Changed the EIP checking way
warden-protocol/helm-charts pull request #58
Opened 2024-10-11 12:30 UTC by mikolajsobolewski

2024-10-11 12:43 UTC, jlehtimaki requested changes
The script in it self is not loaded anywhere.
How are you going to handle other types of deployments, like if/when we use cosmovisor again?

2024-10-16 07:30 UTC, jlehtimaki requested changes

2024-10-16 07:30 UTC, jlehtimaki commented on charts/wardend/scripts/docker-entrypoint.sh
> +  while [ -z "$EIP" ]; do
Have you tested that this works?
AFAIK, script environments run on their own "env" so, basically if the EIP gets set on the system it would not affect this script and it would run indefinitely.

So this script cannot be tested like:
1. Run without EIP set
2. Run again with EIP set

It should be set while the bash is running on a separate window.

2024-10-16 10:54 UTC, mikolajsobolewski commented on charts/wardend/scripts/docker-entrypoint.sh
> +  while [ -z "$EIP" ]; do
Without. EIP
```
+ '[' -n true ']'
+ echo 'EIP_CHECK is set. Waiting for EIP to be populated...'
+ '[' -z '' ']'
+ echo 'EIP is not set yet. Sleeping for 5 seconds...'
+ sleep 5
EIP_CHECK is set. Waiting for EIP to be populated...
EIP is not set yet. Sleeping for 5 seconds...
```
with EIP
```
+ '[' -n true ']'
+ echo 'EIP_CHECK is set. Waiting for EIP to be populated...'
+ '[' -z 10.1.1.1 ']'
+ echo 'EIP is now set. Starting /usr/bin/wardend with flags: '
+ /usr/bin/wardend start
EIP_CHECK is set. Waiting for EIP to be populated...
EIP is now set. Starting /usr/bin/wardend with flags:
```

2024-10-17 07:36 UTC, closed without merging