Move node variables into node & add containersecuritycontext
warden-protocol/helm-charts pull request #62
Opened 2024-10-22 16:07 UTC by mikolajsobolewski

2024-10-23 06:58 UTC, jlehtimaki requested changes

2024-10-23 06:58 UTC, jlehtimaki commented on charts/wardend/templates/statefulset.yml
> +            {{- toYaml . | nindent 12 }}
I think we need to add the default values for these?

2024-10-23 09:05 UTC, mikolajsobolewski commented on charts/wardend/templates/statefulset.yml
> +            {{- toYaml . | nindent 12 }}
I think it isn't necessary, as default we use .Values.podSecurityContext

2024-10-23 10:34 UTC, jlehtimaki requested changes

2024-10-23 10:34 UTC, jlehtimaki commented on charts/wardend/templates/statefulset.yml
>            command: [ "/bin/bash" , "/scripts/init-cosmovisor.sh" ]
This does not work without root privileges due to the `apt install` part, please remove that if it's not necessary.

2024-10-23 10:34 UTC, jlehtimaki commented on charts/wardend/templates/statefulset.yml
> +            {{- toYaml . | nindent 12 }}
Why not, `Slinky` is the only part that has this "special" need for being a privileged user.
Now our defaults are `1000` user/group ID?

2024-10-23 11:19 UTC, jlehtimaki requested changes

2024-10-23 11:19 UTC, jlehtimaki commented on charts/wardend/values.yaml
> +    runAsNonRoot: true
This is not correct, Slinky needs to run as root for the time being.

2024-10-23 11:23 UTC, mikolajsobolewski commented on charts/wardend/templates/statefulset.yml
> +            {{- toYaml . | nindent 12 }}
okay, i removed podSecurityContext and add defaults for container securityContext

2024-10-23 11:24 UTC, mikolajsobolewski commented on charts/wardend/templates/statefulset.yml
>            command: [ "/bin/bash" , "/scripts/init-cosmovisor.sh" ]
apt install part doesn't work because curl already have in image, but i removed this part in script.

2024-10-23 11:26 UTC, mikolajsobolewski commented on charts/wardend/values.yaml
> +    runAsNonRoot: true
For what? As i tested silky great worked as an unprivileged user

2024-10-24 07:17 UTC, jlehtimaki requested changes

2024-10-24 07:17 UTC, jlehtimaki commented on charts/wardend/values.yaml
> +    fsGroup: 1000
fsGroup is not supported parameter here.

2024-10-24 07:17 UTC, jlehtimaki commented on charts/wardend/values.yaml
> +    runAsNonRoot: true
I'm not sure how you tested this but this whole thing fails in numerous places.
`fsgroup` is not a valid parameter.
Then init container cannot even successfully do what it needs:
```
couldn't make client config: mkdir /data/.warden/config: permission denied
```

2024-10-24 12:36 UTC, closed without merging